version: '2'
services:
  logspout:
    image: micahhausler/logspout:gelf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8000:80
    command: gelf://10.0.3.38:12201
    depends_on:
      - graylog
    networks:
      - graylognet
  mongo:
    image: "mongo:3"
    volumes:
      - graylog_data_mongo:/data/db
    networks:
      - graylognet
  graylog:
    image: graylog/graylog:2.3.0-1
    volumes:
      - graylog_data_journal:/usr/share/graylog/data/journal
#      - graylog_config:/usr/share/graylog/data/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://52.2.57.99:9000/api/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://10.0.3.38:9200
    depends_on:
      - mongo
    expose:
      - "12201/udp"
      - "1514/udp"
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"
    networks:
      - graylognet

volumes:
  graylog_data_mongo:
    driver: local
  graylog_data_journal:
    driver: local
#  graylog_config:
#    driver: local

networks:
  graylognet: