version: '2'
services:
  logspout:
    image: micahhausler/logspout:gelf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:80
    command: gelf://graylog:12201
    depends_on:
      - graylog
    networks:
      - graylognet
  mongo:
    image: "mongo:3"
    volumes:
      - graylog_data_mongo:/data/db
    networks:
      - graylognet
  elasticsearch1:
    image: docker.icasei.com.br/elasticsearch:5.5.1
    container_name: elasticsearch1
    environment:
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - graylognet
  elasticsearch2:
    image: docker.icasei.com.br/elasticsearch:5.5.1
    environment:
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - graylognet
  graylog:
    image: graylog/graylog:2.3.0-1
    volumes:
      - graylog_data_journal:/usr/share/graylog/data/journal
#      - graylog_config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch1:9200,http://elasticsearch2:9200
    depends_on:
      - mongo
      - elasticsearch1
      - elasticsearch2
    expose:
      - "12201/udp"
      - "1514/udp"
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"
    networks:
      - graylognet

volumes:
  graylog_data_mongo:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
  graylog_data_journal:
    driver: local
#  graylog_config:
#    driver: local

networks:
  graylognet: